service: dboCFA
frameworkVersion: '3'
plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-west-1
  httpApi:
    cors: true

functions:
  crudId:
    handler: handler.crud
    events:
      - httpApi:
          path: /{entity}/{method}/{id}
          method: any
  crud:
    handler: handler.crud
    events:
      - httpApi:
          path: /{entity}/{method}
          method: any
# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
